name: Code Review with Checkstyle

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

      - name: Run Checkstyle
        run: mvn clean verify
        continue-on-error: true

      - name: Run Checkstyle
        run: mvn clean verify
        continue-on-error: true   # cho chạy tiếp để comment

      - name: Comment Checkstyle
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: target/checkstyle-result.xml

      # 🔥 BẮT BUỘC phải fail lại
      - name: Fail if Checkstyle failed
        run: |
          if grep -q "<error" target/checkstyle-result.xml; then
            echo "Checkstyle violations found"
            exit 1
          fi